package zhwb.study;
import zhwb.drools.domain.Employer;
import zhwb.drools.domain.Employee;

rule "display1"
	salience 3
	when
		$m:Employer();
	then
		System.out.println(""+$m.count());
end

rule "add"
	salience 4
	no-loop true
	when
		$e:Employee();
		$m:Employer();
	then
		$m.addEmployee($e);
		System.out.println("add:" + $m.getEmployees());
		update($m);
end

rule "display"
	salience 2
	when
		$m:Employer();
	then
		System.out.println("dispay:"+$m.getEmployees());
end

rule "contains"
	salience 1
	when
		$e:Employee(age < 30);
		$m:Employer(employees contains $e);
	then

		System.out.println("contains:" + $e.getName());
end