package test

import domain.From;
import java.util.List;

rule test_and
    when
        /*如何将判断和赋值放在一起*/
//        From(clientIp: ips) and From(clientIp != null) and From(clientNums:nums) and From(clientNums!=null)
        ((From(clientIp: ips) and From(clientIp != null))
 and
        (From(clientNums:nums) and From(clientNums!=null)))
    then
        System.out.println("找到想要的值从数据中:" + clientIp + ", "+clientNums);
end

/*rule test_and_0
    when
        From(ips!=null)
        From(ips.length>0)
    then
        System.out.println("非空则报错");
end*/

rule test_and_1
    when
        From(notnullIP:ips!=null)
        From(notnullIP.length>0)
    then
        System.out.println("非空则报错");
end

rule test_and_2
    when
        f:From(ips!=null)
        From(f.ips.length>0)
    then
        System.out.println("非空则报错");
end

