package test

import domain.Person;
import domain.Address;
import java.util.List;

rule "Assign people in North Carolina (NC) to sales region 1"
ruleflow-group "test"
auto-focus true
lock-on-active true
when
    $p : Person()
    $a : Address(state == "ShanDong") from $p.address
then
    System.out.println("run ShanDong");
    modify ($p) {
        setSaleRegion(1)
    } // Assign person to sales region 1 in a modify block
end

rule "Apply a discount to people in the city of Raleigh"
ruleflow-group "test"
auto-focus true
lock-on-active true
when
    $p : Person()
    $a : Address(city == "Qingdao") from $p.address
then
    System.out.println("run Qingdao");
    modify ($p) {
        setDiscount(0.9)
    } // Apply discount to person in a modify block
end

rule "Assign people in North Carolina (NC) to sales region 1 1"
ruleflow-group "test"
auto-focus true
lock-on-active true
when
    $p : Person(address.state == "ShanDong" )
then
   System.out.println("run ShanDong");
       modify ($p) {
           setSaleRegion(1)
       } // Assign person to sales region 1 in a modify block
end

rule "Apply a discount to people in the city of Raleigh 1"
ruleflow-group "test"
auto-focus true
lock-on-active true
when
    $p : Person(address.city == "Qingdao" )
then
    System.out.println("run Qingdao");
        modify ($p) {
            setDiscount(0.9)
        } // Apply discount to person in a modify block
end

