package test

import zhwb.drools.domain.For;
import java.util.List;

rule test_for
    when
        f:For()
        $sum:Double() from accumulate (i:Integer(i==1) from f.nums, sum(i))
        $sums:Double() from accumulate (i:Integer() from f.nums, sum(i))
        $ip:List() from collect (str:String() from f.ips.split(","))
        $newIp:List() from collect(str:String(str == "1") from f.ips.split(","))
    then
        System.out.println("sum:" + $sum);
        System.out.println("sums:" + $sums);
        System.out.println("string split to collection:" + $ip);
        System.out.println("符合条件的集合:" + $newIp);
        System.out.println("符合条件的个数:" + $newIp.size());
end

