package test
import java.util.List

query "query fact count" Customer();
end

declare Customer
    id:int
    name:String
    age:int
end
rule "rule1"
    salience 1
    when
        eval(true)
        $customer:Customer(name=="zhangsan");
    then
        System.out.println("----------"+$customer.getName());
end
rule "rule2"
    salience 2
    when
    eval(true)
        $customer:Customer(name=="zhangsan");
    then
        System.out.println("----------"+$customer.getName());
end